"""add_context_tree_checkpoints

Revision ID: b60ef06f1fcf
Revises: c7e2a3f1b4d8
Create Date: 2026-03-03 09:01:29.968767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60ef06f1fcf'
down_revision: Union[str, None] = 'c7e2a3f1b4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_tree_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('tree_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('leaf_count', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['context_tree_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_tree_checkpoints_org_id'), 'context_tree_checkpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_context_tree_checkpoints_run_id'), 'context_tree_checkpoints', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_tree_checkpoints_run_id'), table_name='context_tree_checkpoints')
    op.drop_index(op.f('ix_context_tree_checkpoints_org_id'), table_name='context_tree_checkpoints')
    op.drop_table('context_tree_checkpoints')
    # ### end Alembic commands ###
